spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iprecord?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern : /**
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000
    port: 6379
    host: 127.0.0.1
    timeout: 1000
    #SpringCache-redis
    cache:
      cache-names: redisCache
      type: redis
      redis:
        key-prefix :
        use-key-prefix: false
        time-to-live: 600000
  activemq:
    #activemq连接地址
    broker-url: tcp://localhost:61616
    #user户名
    user: admin
    #密码
    password: admin
    #连接池属性
    pool:
      enabled: true
      max-connections: 50
  jms:
    #是否开启发布订阅模式
    pub-sub-domain: true
    #默认目的地址
    template:
      default-destination: activemq.default.destination
mybatis:
  #config-location:  classpath:mybatis-config.xml
  type-aliases-package: cn.loveyx815.userscript.entity
  mapper-locations: classpath:mapper/*.xml

